#include "Instructions.h"
#include "utils.h"
#include <iostream>

std::unordered_map<std::string, Instruction> instructionSet = {
    {"ACI", Instruction("ACI", 0xCE, 2)},
    {"ADC A", Instruction("ADC A", 0x8F, 1)},
    {"ADC B", Instruction("ADC B", 0x88, 1)},
    {"ADC C", Instruction("ADC C", 0x89, 1)},
    {"ADC D", Instruction("ADC D", 0x8A, 1)},
    {"ADC E", Instruction("ADC E", 0x8B, 1)},
    {"ADC H", Instruction("ADC H", 0x8C, 1)},
    {"ADC L", Instruction("ADC L", 0x8D, 1)},
    {"ADC M", Instruction("ADC M", 0x8E, 1)},
    {"ADD A", Instruction("ADD A", 0x87, 1)},
    {"ADD B", Instruction("ADD B", 0x80, 1)},
    {"ADD C", Instruction("ADD C", 0x81, 1)},
    {"ADD D", Instruction("ADD D", 0x82, 1)},
    {"ADD E", Instruction("ADD E", 0x83, 1)},
    {"ADD H", Instruction("ADD H", 0x84, 1)},
    {"ADD L", Instruction("ADD L", 0x85, 1)},
    {"ADD M", Instruction("ADD M", 0x86, 1)},
    {"ADI", Instruction("ADI", 0xC6, 2)},
    {"ANA A", Instruction("ANA A", 0xA7, 1)},
    {"ANA B", Instruction("ANA B", 0xA0, 1)},
    {"ANA C", Instruction("ANA C", 0xA1, 1)},
    {"ANA D", Instruction("ANA D", 0xA2, 1)},
    {"ANA E", Instruction("ANA E", 0xA3, 1)},
    {"ANA H", Instruction("ANA H", 0xA4, 1)},
    {"ANA L", Instruction("ANA L", 0xA5, 1)},
    {"ANA M", Instruction("ANA M", 0xA6, 1)},
    {"ANI", Instruction("ANI", 0xE6, 2)},
    {"CALL", Instruction("CALL", 0xCD, 3)},
    {"CC", Instruction("CC", 0xDC, 3)},
    {"CM", Instruction("CM", 0xFC, 3)},
    {"CMA", Instruction("CMA", 0x2F, 1)},
    {"CMC", Instruction("CMC", 0x3F, 1)},
    {"CMP A", Instruction("CMP A", 0xBF, 1)},
    {"CMP B", Instruction("CMP B", 0xB8, 1)},
    {"CMP C", Instruction("CMP C", 0xB9, 1)},
    {"CMP D", Instruction("CMP D", 0xBA, 1)},
    {"CMP E", Instruction("CMP E", 0xBB, 1)},
    {"CMP H", Instruction("CMP H", 0xBC, 1)},
    {"CMP L", Instruction("CMP L", 0xBD, 1)},
    {"CMP M", Instruction("CMP M", 0xBD, 1)},
    {"CNC", Instruction("CNC", 0xD4, 3)},
    {"CNZ", Instruction("CNZ", 0xC4, 3)},
    {"CP", Instruction("CP", 0xF4, 3)},
    {"CPE", Instruction("CPE", 0xEC, 3)},
    {"CPI", Instruction("CPI", 0xFE, 2)},
    {"CPO", Instruction("CPO", 0xE4, 3)},
    {"CZ", Instruction("CZ", 0xCC, 3)},
    {"DAA", Instruction("DAA", 0x27, 1)},
    {"DAD B", Instruction("DAD B", 0x09, 1)},
    {"DAD D", Instruction("DAD D", 0x19, 1)},
    {"DAD H", Instruction("DAD H", 0x29, 1)},
    {"DAD SP", Instruction("DAD SP", 0x39, 1)},
    {"DCR A", Instruction("DCR A", 0x3D, 1)},
    {"DCR B", Instruction("DCR B", 0x05, 1)},
    {"DCR C", Instruction("DCR C", 0x0D, 1)},
    {"DCR D", Instruction("DCR D", 0x15, 1)},
    {"DCR E", Instruction("DCR E", 0x1D, 1)},
    {"DCR H", Instruction("DCR H", 0x25, 1)},
    {"DCR L", Instruction("DCR L", 0x2D, 1)},
    {"DCR M", Instruction("DCR M", 0x35, 1)},
    {"MOV D, B", Instruction("MOV D, B", 0x50, 1)},
    {"MOV D, C", Instruction("MOV D, C", 0x51, 1)},
    {"MOV D, D", Instruction("MOV D, D", 0x52, 1)},
    {"MOV D, E", Instruction("MOV D, E", 0x53, 1)},
    {"MOV D, H", Instruction("MOV D, H", 0x54, 1)},
    {"MOV D, L", Instruction("MOV D, L", 0x55, 1)},
    {"MOV D, M", Instruction("MOV D, M", 0x56, 1)},
    {"MOV E, A", Instruction("MOV E, A", 0x5F, 1)},
    {"MOV E, B", Instruction("MOV E, B", 0x58, 1)},
    {"MOV E, C", Instruction("MOV E, C", 0x59, 1)},
    {"MOV E, D", Instruction("MOV E, D", 0x5A, 1)},
    {"MOV E, E", Instruction("MOV E, E", 0x5B, 1)},
    {"MOV E, H", Instruction("MOV E, H", 0x5C, 1)},
    {"MOV E, L", Instruction("MOV E, L", 0x5D, 1)},
    {"MVI A",    Instruction("MVI A", 0x3E, 1)}
};

std::unordered_map<std::string, std::function<void()>> instructionHandlers = {
    {"MVI A", [] { debug("MVI A", 0); }}
};
