#include "../Headers/Head_2.h"
#include "../Headers/Instructions.h"
#include "../Headers/utils.h"


std::map<std::string, Instruction> instructionSet = {
    {"ACI", Instruction("ACI", decodeACI, 2)},
    {"ADC", Instruction("ADC", decodeADC, 1)},
    {"ADD", Instruction("ADD", decodeADD, 1)},
    {"ADI", Instruction("ADI", decodeADI, 2)},
    {"ANA", Instruction("ANA", decodeANA, 1)},
    {"ANI", Instruction("ANI", decodeANI, 2)},
    {"CALL", Instruction("CALL", decodeCALL, 3)},
    {"CC", Instruction("CC", decodeCC, 3)},
    {"CM", Instruction("CM", decodeCM, 3)},
    {"CMA", Instruction("CMA", decodeCMA, 1)},
    {"CMC", Instruction("CMC", decodeCMC, 1)},
    {"CMP", Instruction("CMP", decodeCMP, 1)},
    {"CNC", Instruction("CNC", decodeCNC, 3)},
    {"CNZ", Instruction("CNZ", decodeCNZ, 3)},
    {"CP", Instruction("CP", decodeCP, 3)},
    {"CPE", Instruction("CPE", decodeCPE, 3)},
    {"CPI", Instruction("CPI", decodeCPI, 2)},
    {"CPO", Instruction("CPO", decodeCPO, 3)},
    {"CZ", Instruction("CZ", decodeCZ, 3)},
    {"DAA", Instruction("DAA", decodeDAA, 1)},
    {"DAD", Instruction("DAD", decodeDAD, 1)},
    {"DCR", Instruction("DCR", decodeDCR, 1)},
    {"DCX", Instruction("DCX", decodeDCX, 1)},
    {"DI", Instruction("DI", decodeDI, 1)},
    {"EI", Instruction("EI", decodeEI, 1)},
    {"INR", Instruction("INR", decodeINR, 1)},
    {"INX", Instruction("INX", decodeINX, 1)},
    {"JC", Instruction("JC", decodeJC, 3)},
    {"JM", Instruction("JM", decodeJM, 3)},
    {"JMP", Instruction("JMP", decodeJMP, 3)},
    {"JNC", Instruction("JNC", decodeJNC, 3)},
    {"JNZ", Instruction("JNZ", decodeJNZ, 3)},
    {"JP", Instruction("JP", decodeJP, 3)},
    {"JPE", Instruction("JPE", decodeJPE, 3)},
    {"JPO", Instruction("JPO", decodeJPO, 3)},
    {"JZ", Instruction("JZ", decodeJZ, 3)},
    {"LDA", Instruction("LDA", decodeLDA, 3)},
    {"LDAX", Instruction("LDAX", decodeLDAX, 1)},
    {"LHLD", Instruction("LHLD", decodeLHLD, 3)},
    {"LXI", Instruction("LXI", decodeLXI, 3)},
    {"MOV", Instruction("MOV", decodeMOV, 1)},
    {"MVI", Instruction("MVI", decodeMVI, 2)},
    {"NOP", Instruction("NOP", decodeNOP, 1)},
    {"ORA", Instruction("ORA", decodeORA, 1)},
    {"ORI", Instruction("ORI", decodeORI, 2)},
    {"PCHL", Instruction("PCHL", decodePCHL, 1)},
    {"POP", Instruction("POP", decodePOP, 1)},
    {"PUSH", Instruction("PUSH", decodePUSH, 1)},
    {"RAL", Instruction("RAL", decodeRAL, 1)},
    {"RAR", Instruction("RAR", decodeRAR, 1)},
    {"RC", Instruction("RC", decodeRC, 1)},
    {"RET", Instruction("RET", decodeRET, 1)},
    {"RIM", Instruction("RIM", decodeRIM, 1)},
    {"RLC", Instruction("RLC", decodeRLC, 1)},
    {"RM", Instruction("RM", decodeRM, 1)},
    {"RNC", Instruction("RNC", decodeRNC, 1)},
    {"RNZ", Instruction("RNZ", decodeRNZ, 1)},
    {"RP", Instruction("RP", decodeRP, 1)},
    {"RPE", Instruction("RPE", decodeRPE, 1)},
    {"RPO", Instruction("RPO", decodeRPO, 1)},
    {"RRC", Instruction("RRC", decodeRRC, 1)},
    {"RST", Instruction("RST", decodeRST, 1)},
    {"RZ", Instruction("RZ", decodeRZ, 1)},
    {"SBB", Instruction("SBB", decodeSBB, 1)},
    {"SBI", Instruction("SBI", decodeSBI, 2)},
    {"SHLD", Instruction("SHLD", decodeSHLD, 3)},
    {"SIM", Instruction("SIM", decodeSIM, 1)},
    {"SPHL", Instruction("SPHL", decodeSPHL, 1)},
    {"STA", Instruction("STA", decodeSTA, 3)},
    {"STAX B", Instruction("STAX B", decodeSTAXB, 1)},
    {"STAX D", Instruction("STAX D", decodeSTAXD, 1)},
    {"STC", Instruction("STC", decodeSTC, 1)},
    {"SUB", Instruction("SUB", decodeSUB, 1)},
    {"SUI", Instruction("SUI", decodeSUI, 2)},
    {"XCHG", Instruction("XCHG", decodeXCHG, 1)},
    {"XTHL", Instruction("XTHL", decodeXTHL, 1)},
    {"XRA", Instruction("XRA", decodeXRA, 1)},
    {"XRI", Instruction("XRI", decodeXRI, 2)},
    {"IN", Instruction("IN", decodeIN, 2)},
    {"OUT", Instruction("OUT", decodeOUT, 2)},
    {"HLT", Instruction("HLT", decodeHLT, 1)}
};