#include "../Headers/Head_1.h"
#include "../Headers/Instructions.h"
#include "../Headers/utils.h"


std::map<std::string, Instruction> instructionSet = {
    {"ACI", Instruction("ACI", 0x00, 2)}, 
    {"ADC", Instruction("ADC", 0x01, 1)}, 
    {"ADD", Instruction("ADD", 0x02, 1)}, 
    {"ADI", Instruction("ADI", 0x03, 2)}, 
    {"ANA", Instruction("ANA", 0x04, 1)}, 
    {"ANI", Instruction("ANI", 0x05, 2)}, 
    {"CALL", Instruction("CALL", 0x06, 3)}, 
    {"CC", Instruction("CC", 0x07, 3)}, 
    {"CM", Instruction("CM", 0x08, 3)}, 
    {"CMA", Instruction("CMA", 0x09, 1)}, 
    {"CMC", Instruction("CMC", 0x0A, 1)}, 
    {"CMP", Instruction("CMP", 0x0B, 1)}, 
    {"CNC", Instruction("CNC", 0x0C, 3)}, 
    {"CNZ", Instruction("CNZ", 0x0D, 3)}, 
    {"CP", Instruction("CP", 0x0E, 3)}, 
    {"CPE", Instruction("CPE", 0x0F, 3)}, 
    {"CPI", Instruction("CPI", 0x10, 2)}, 
    {"CPO", Instruction("CPO", 0x11, 3)}, 
    {"CZ", Instruction("CZ", 0x12, 3)}, 
    {"DAA", Instruction("DAA", 0x13, 1)}, 
    {"DAD", Instruction("DAD", 0x14, 1)}, 
    {"DCR", Instruction("DCR", 0x15, 1)}, 
    {"DCX", Instruction("DCX", 0x16, 1)}, 
    {"DI", Instruction("DI", 0x17, 1)}, 
    {"EI", Instruction("EI", 0x18, 1)}, 
    {"INR", Instruction("INR", 0x19, 1)}, 
    {"INX", Instruction("INX", 0x1A, 1)}, 
    {"JC", Instruction("JC", 0x1B, 3)}, 
    {"JM", Instruction("JM", 0x1C, 3)}, 
    {"JMP", Instruction("JMP", 0x1D, 3)}, 
    {"JNC", Instruction("JNC", 0x1E, 3)}, 
    {"JNZ", Instruction("JNZ", 0x1F, 3)}, 
    {"JP", Instruction("JP", 0x20, 3)}, 
    {"JPE", Instruction("JPE", 0x21, 3)}, 
    {"JPO", Instruction("JPO", 0x22, 3)}, 
    {"JZ", Instruction("JZ", 0x23, 3)}, 
    {"LDA", Instruction("LDA", 0x24, 3)}, 
    {"LDAX", Instruction("LDAX", 0x25, 1)}, 
    {"LHLD", Instruction("LHLD", 0x26, 3)}, 
    {"LXI", Instruction("LXI", 0x27, 3)}, 
    {"MOV", Instruction("MOV", 0x28, 1)}, 
    {"MVI", Instruction("MVI", 0x29, 2)}, 
    {"NOP", Instruction("NOP", 0x2A, 1)}, 
    {"ORA", Instruction("ORA", 0x2B, 1)}, 
    {"ORI", Instruction("ORI", 0x2C, 2)}, 
    {"PCHL", Instruction("PCHL", 0x2D, 1)}, 
    {"POP", Instruction("POP", 0x2E, 1)}, 
    {"PUSH", Instruction("PUSH", 0x2F, 1)}, 
    {"RAL", Instruction("RAL", 0x30, 1)}, 
    {"RAR", Instruction("RAR", 0x31, 1)}, 
    {"RC", Instruction("RC", 0x32, 1)}, 
    {"RET", Instruction("RET", 0x33, 1)}, 
    {"RIM", Instruction("RIM", 0x34, 1)}, 
    {"RLC", Instruction("RLC", 0x35, 1)}, 
    {"RM", Instruction("RM", 0x36, 1)}, 
    {"RNC", Instruction("RNC", 0x37, 1)}, 
    {"RNZ", Instruction("RNZ", 0x38, 1)}, 
    {"RP", Instruction("RP", 0x39, 1)}, 
    {"RPE", Instruction("RPE", 0x3A, 1)}, 
    {"RPO", Instruction("RPO", 0x3B, 1)}, 
    {"RRC", Instruction("RRC", 0x3C, 1)}, 
    {"RST", Instruction("RST", 0x3D, 1)}, 
    {"RZ", Instruction("RZ", 0x3E, 1)}, 
    {"SBB", Instruction("SBB", 0x3F, 1)}, 
    {"SBI", Instruction("SBI", 0x40, 2)}, 
    {"SHLD", Instruction("SHLD", 0x41, 3)}, 
    {"SIM", Instruction("SIM", 0x42, 1)}, 
    {"SPHL", Instruction("SPHL", 0x43, 1)}, 
    {"STA", Instruction("STA", 0x44, 3)}, 
    {"STAX B", Instruction("STAX B", 0x45, 1)}, 
    {"STAX D", Instruction("STAX D", 0x46, 1)}, 
    {"STC", Instruction("STC", 0x47, 1)}, 
    {"SUB", Instruction("SUB", 0x48, 1)}, 
    {"SUI", Instruction("SUI", 0x49, 2)}, 
    {"XCHG", Instruction("XCHG", 0x4A, 1)}, 
    {"XTHL", Instruction("XTHL", 0x4B, 1)}, 
    {"XRA", Instruction("XRA", 0x4C, 1)}, 
    {"XRI", Instruction("XRI", 0x4D, 2)}, 
    {"IN", Instruction("IN", 0x4E, 2)}, 
    {"OUT", Instruction("OUT", 0x4F, 2)}, 
    {"HLT", Instruction("HLT", 0x50, 1)}, 
};

std::map<std::string, std::function<void()>> instructionHandlers = {
    //{"MVI A", [] { /*debug*/("MVI A", 0); }}
};
